server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location /reads/ {
        try_files $uri $uri/ /reads/index.html;
    }

    location = /reads {
        return 301 /reads/;
    }

    location = / {
        return 301 /reads/;
    }

    error_page 404 /reads/404.html;
}
